# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledgepoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Secondgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('firstgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myp.Firstgroup')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='secondgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myp.Secondgroup'),
        ),
    ]
